# Generated by Django 4.2.7 on 2025-12-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('sinopse', models.TextField(blank=True)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='livraria/capas/')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='livraria/livros/pdf/')),
                ('arquivo_epub', models.FileField(blank=True, null=True, upload_to='livraria/livros/epub/')),
                ('arquivo_mobi', models.FileField(blank=True, null=True, upload_to='livraria/livros/mobi/')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendente', max_length=20)),
                ('codigo_transacao', models.CharField(blank=True, max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
