# Generated by Django 4.2.7 on 2025-12-29 00:47

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('editado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Resposta do Fórum',
                'verbose_name_plural': 'Respostas do Fórum',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TopicoForum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', ckeditor.fields.RichTextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fixado', models.BooleanField(default=False)),
                ('fechado', models.BooleanField(default=False)),
                ('visualizacoes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tópico do Fórum',
                'verbose_name_plural': 'Tópicos do Fórum',
                'ordering': ['-fixado', '-criado_em'],
            },
        ),
    ]
