# Generated by Django 4.2.7 on 2025-12-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AconselhamentoPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem_inicial', models.TextField()),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('aceito', 'Aceito'), ('em_andamento', 'Em Andamento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Aconselhamento Pastoral',
                'verbose_name_plural': 'Aconselhamentos Pastorais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CompromissoOracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compromisso de Oração',
                'verbose_name_plural': 'Compromissos de Oração',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemAconselhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem de Aconselhamento',
                'verbose_name_plural': 'Mensagens de Aconselhamento',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PedidoOracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('atendido', 'Atendido'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('anonimo', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pedido de Oração',
                'verbose_name_plural': 'Pedidos de Oração',
                'ordering': ['-criado_em'],
            },
        ),
    ]
