# Generated by Django 4.2.7 on 2025-12-29 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apoio_espiritual', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidooracao',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_oracao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensagemaconselhamento',
            name='aconselhamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='apoio_espiritual.aconselhamentopastoral'),
        ),
        migrations.AddField(
            model_name='mensagemaconselhamento',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compromissooracao',
            name='membro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compromissooracao',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compromissos', to='apoio_espiritual.pedidooracao'),
        ),
        migrations.AddField(
            model_name='aconselhamentopastoral',
            name='lider_espiritual',
            field=models.ForeignKey(limit_choices_to={'perfil_membro': 'lider_espiritual'}, on_delete=django.db.models.deletion.CASCADE, related_name='aconselhamentos_atendidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aconselhamentopastoral',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aconselhamentos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='compromissooracao',
            unique_together={('pedido', 'membro')},
        ),
    ]
