# Generated by Django 4.2.7 on 2025-12-29 00:47

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SugestaoPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('artigo', 'Artigo'), ('devocional', 'Devocional'), ('podcast', 'Podcast')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugestão de Pauta',
                'verbose_name_plural': 'Sugestões de Pauta',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('url_externa', models.URLField(blank=True, help_text='URL para plataformas como Youtube, Spotify, etc', null=True)),
                ('permite_comentarios', models.BooleanField(default=True)),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='vdflix/pdf/')),
                ('links_externos', models.TextField(blank=True, help_text='Links externos separados por vírgula')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('plataforma', models.CharField(blank=True, help_text='Ex: Spotify, Youtube, etc', max_length=100)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linhas_teologicas', models.ManyToManyField(blank=True, to='usuarios.linhateologica')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linhas_teologicas', models.ManyToManyField(blank=True, to='usuarios.linhateologica')),
            ],
            options={
                'verbose_name': 'Plataforma',
                'verbose_name_plural': 'Plataformas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('url_externa', models.URLField(blank=True, help_text='URL para plataformas como Youtube, Spotify, etc', null=True)),
                ('permite_comentarios', models.BooleanField(default=True)),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='vdflix/pdf/')),
                ('links_externos', models.TextField(blank=True, help_text='Links externos separados por vírgula')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linhas_teologicas', models.ManyToManyField(blank=True, to='usuarios.linhateologica')),
            ],
            options={
                'verbose_name': 'EBD',
                'verbose_name_plural': 'EBDs',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Devocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('url_externa', models.URLField(blank=True, help_text='URL para plataformas como Youtube, Spotify, etc', null=True)),
                ('permite_comentarios', models.BooleanField(default=True)),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='vdflix/pdf/')),
                ('links_externos', models.TextField(blank=True, help_text='Links externos separados por vírgula')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linhas_teologicas', models.ManyToManyField(blank=True, to='usuarios.linhateologica')),
            ],
            options={
                'verbose_name': 'Devocional',
                'verbose_name_plural': 'Devocionais',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('url', models.URLField()),
                ('plataforma', models.CharField(blank=True, help_text='Ex: Udemy, Coursera, etc', max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='vdflix/cursos/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linhas_teologicas', models.ManyToManyField(blank=True, to='usuarios.linhateologica')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Culto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('url_externa', models.URLField(blank=True, help_text='URL para plataformas como Youtube, Spotify, etc', null=True)),
                ('permite_comentarios', models.BooleanField(default=True)),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='vdflix/pdf/')),
                ('links_externos', models.TextField(blank=True, help_text='Links externos separados por vírgula')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linhas_teologicas', models.ManyToManyField(blank=True, to='usuarios.linhateologica')),
            ],
            options={
                'verbose_name': 'Culto',
                'verbose_name_plural': 'Cultos',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ebd', 'EBD'), ('devocional', 'Devocional'), ('comentando', 'Comentando')], max_length=20)),
                ('objeto_id', models.PositiveIntegerField()),
                ('comentario', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comentando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('url_externa', models.URLField(blank=True, help_text='URL para plataformas como Youtube, Spotify, etc', null=True)),
                ('permite_comentarios', models.BooleanField(default=True)),
                ('conteudo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='vdflix/pdf/')),
                ('links_externos', models.TextField(blank=True, help_text='Links externos separados por vírgula')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=False)),
                ('revisado', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('noticias', 'Notícias'), ('livros', 'Livros'), ('artigos', 'Artigos'), ('biblia', 'Bíblia')], max_length=20)),
                ('cadastrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('linhas_teologicas', models.ManyToManyField(blank=True, to='usuarios.linhateologica')),
            ],
            options={
                'verbose_name': 'Comentando',
                'verbose_name_plural': 'Comentando',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ebd', 'EBD'), ('devocional', 'Devocional'), ('comentando', 'Comentando'), ('podcast', 'Podcast'), ('culto', 'Culto'), ('plataforma', 'Plataforma'), ('curso', 'Curso')], max_length=20)),
                ('objeto_id', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item de Playlist',
                'verbose_name_plural': 'Itens de Playlist',
                'ordering': ['-criado_em'],
                'unique_together': {('usuario', 'tipo', 'objeto_id')},
            },
        ),
    ]
